# Generated by Django 5.2 on 2026-01-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_reservation_agree_reservation_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='children',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
