# Generated by Django 5.2 on 2025-04-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_treatment_remove_wellnessbooking_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='treatment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reservation_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
