# Generated by Django 5.2 on 2025-04-21 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttable',
            name='is_available',
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='table_number',
            field=models.CharField(default=10, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restauranttable')),
            ],
        ),
        migrations.DeleteModel(
            name='RestaurantBooking',
        ),
    ]
