# Generated by Django 5.2 on 2025-04-21 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_restauranttable_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreservation',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
