# Generated by Django 5.2 on 2025-04-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurantreservation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreservation',
            name='reservation_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
